name: Hello, World
 
# Controls when the workflow will run, in this case manually
on: workflow_dispatch

jobs:
  PrintHelloWorld:
    name: Print Hello, World!
    runs-on: windows-latest
    steps: 
    - run: echo "Hello, World!"

    
 
